### ISSUE TITLE
1 browser window instead of [new tab -> new window] method proposal

### ISSUE THREAD

**Issue by mokanfar** [bdc34/helm-taskswitch#2]
This way linked below to do it in 1 chromium window and activate tab through shell script works using jq and some wmctrl bash script:

https://unix.stackexchange.com/a/520936/282423

Question is would the following idea work: 
 - Get output of tabs from jq (this is easy)
 - Push to mini-buffer list of entries of tab title (considered virtual entries since they do not represent actual Xwindow's ?)
 - Have those entries (mini-buffer virtual entries that represent open tabs) pass data to a shell script that activates browser and switches to tab selected from mini-buffer

**Comment by bdc34** [comment]
I don't use chromium but this sounds good.  If you can get the list of tabs+windowID and know bring the tab to the front of a chromium window you'll be able to do this.

I would do this by making a new helm source and add it to the list of sources here:
https://github.com/bdc34/helm-taskswitch/blob/59f7cb99defa6e6bf6e7d599559fa8d5786cf8a9/helm-taskswitch.el#L246

Here is a good example of calling a program to make a list of candidates:
https://github.com/xuchunyang/helm-chrome-control/blob/master/helm-chrome-control.el

**Comment by mokanfar** [comment]
thank you for the guidance it really pointed me in right direction.

**Comment by bdc34** [comment]
Send me a PR if you can.
